### ISSUE TITLE
Robot with id 0 does not do anything in grSim

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_proto#13]
Robot with id 0 does not work. After some debugging I found that the problems was in the grsim code. 

The files generated by grsim contain a `packet.command.hasId()` function, which is an autogenerated function that returns true if the id is explicitly set. For robot 0 the id matches it's default value, probably causing the fact that `packet.command.hasId()` returns false (and thus the packet remains unused). 

I fixed this with a rather ugly statement in grsim (sslworld.h) by instead checking for `has_id()`, I check for `id()` and if it has values between 0 and 15.

**Comment by rolfvdhulst** [comment]
You can just check .hasId() and then just check the ID right? That seems like the proper way to do it

**Comment by mrlukasbos** [comment]
hasId() does exist in the generated message from grsim, but it does not exist in the generated message from roboteam_ai, thus, it is never set to true for id 0.

**Comment by rolfvdhulst** [comment]
hmm that's a problem with grSim I would say
