### ISSUE TITLE
field.getLeftPenaltyLine (and others!) not actually working

### ISSUE THREAD

**Issue by mrlukasbos** [RoboTeamTwente/roboteam_proto#17]
The left penalty line is interpreted in roboteam_ai as 'the left line after the conversion', so it is NOT the left line from the incoming field data!! This is actually incorrect, though easily fixed by just not inverting them when they come in...

**Comment by rolfvdhulst** [comment]
I propose we simply make an inverse function on Field that literally swaps the left with the right line

**Comment by mrlukasbos** [comment]
This is an issue for AI and has been looked into
