### ISSUE TITLE
Code review:

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_proto#21]
I cannot review it from a PR or so so I'll do it like this.

Comment 1
_______________
The following lines from CMakeLists.txt are a bit black magic to me:
89-92
target_include_directories(roboteam_proto PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>
        PRIVATE src )
________________

Make the following explicitly all PUBLIC (so do:
PUBLIC ${PROTOBUF_LIBRARIES}
PUBLIC ${ZeroMQ_LIBRARIES}
etc.

CMakeLists 82-88
target_link_libraries(roboteam_proto
        PUBLIC
        ${PROTOBUF_LIBRARIES}
        ${ZeroMQ_LIBRARIES}
        ${ZMQPP_LIBRARIES}
        )
_____________________

PROTOBUF_GENERATE_CPP Can be in lowercase, capitals is old CMake style

**Comment by mrlukasbos** [comment]
i fixed the PUBLIC statements. I the 'black magic' lines where an attempt to make the includes like 'roboteam_proto/subscriber.h' but it somehow does not work here where this does work for other repositories.
